language: node_js
node_js:
  - lts/*

cache:
  directories:
    - "node_modules"

before_script:
  - npm install

script:
  - npm build
  - npm test-only
  - npm typedoc

after_success:
  - npm publish

deploy:    
  - provider: releases
    api_key:
      secure: ozkdQjIFJqyzLaX1FNTn/nP+CpuQa9+HoO9pxdMYSNrRn4AWb1WBl37/76QBLBI6ehvRLqPolbz32JxUmyYW/HMuDqI+8vlE2i5iOy5DZHvSayU5U8GwzHg8ibSfXpnEwc2fMmnOEdQeEjnRRU9Aa2k1/8B/MVa6ouF9jjpt+g9tZeXyvitBndD9SlpHb/zlEfiGTjPWHXABBu6K1omWotClbDpr3u5PhljZiCMOwV6gi8FAXTcV9Q/JXp29d9kDlrLUFmAAh6rLaBCAMrum9AnLtEht85YzxZEZAgfnuqHLf77Z65u1J7mLe0rIYXCal1q/Kn2dzg2HXPChvaZqbXFxOQ2V1WoNiyqtYE9tdYIbDAaM3Igzq+WSovrAHil8aBeWXeFdUS+AgQL2yEu/KiV0ggnrviOV6gvVlDRMEbXEg2+rkvX+qeDnlriB/oS8v5sWiPVaVbP6YfBFfmG2VGKsHDdXonG7/id5aLIQ4t9q2IFgKe/qO8hOkZMIMScFkwrPleNpqqo0VvKPmCS07S9cEMqimXkj18Vmh6rMM0w6yt0vjpOT9NjRFWn/MvAGH0dLBO5Jm8z2wFjXggNw3XiglYy8EUxYQunvhJEZOmFtls5g5rSNVfTuZsjoOYOye6DrdtewmB7yzVOGgBaBVUsIr0POxQv+x238rkwfSyo=
    skip_cleanup: true
    on:
      repo: sualeh/pointlocation6709-ts
      branch: master
      tags: true
    file_glob: true
    file: 
      - "pointlocation6709-ts-*.tgz"
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    verbose: true
    on:
      repo: sualeh/pointlocation6709-ts
      branch: master
      tags: true
    local_dir: "./docs"
    email: "sualeh@hotmail.com"
    name: "Sualeh Fatehi"
 
