name: Create Release

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '*'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-[A-Z]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-node
      name: Setup Node 14.x
      uses: actions/setup-node@v2
      # Setup .npmrc file to publish to npm
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'

# BUILD
    - id: build
      name: Build and test
      run: |
        # Build
        npm install -g typescript
        npm install
        npm run build
        npm test
        npm run coverage
    - id: docs
      name: Generate documentation
      run: |
        # Generate documentation
        npm run typedoc
        touch ./docs/.nojekyll

# PUBLISH WEBSITE TO GITHUB PAGES
    - id: pubish-website
      name: Publish website to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true
        user_name: 'Sualeh Fatehi'
        user_email: 'sualeh@hotmail.com'
        commit_message: 'Point Location 6709 Website ${{ github.sha }}'

# CREATE GITHUB RELEASE AND ADD ASSETS
    - id: create-release
      name: Create GitHub release
      uses: actions/create-release@latest
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Point Location 6709 (Typescript) Release ${{ github.sha }}
        draft: false
        prerelease: false

# PUBLISH TO NPM REGISTRY
    - id: publish
      name: Publish to NPM
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        # Publish to NPM
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
